---
title: "Resources"
---

## Learning Pathways

### Start Here: Methods in Causal Inference Series

A four-part tutorial series published in *Evolutionary Human Sciences* that provides a systematic introduction to causal inference methods.

#### Part 1: [Causal Diagrams and Confounding](https://www.cambridge.org/core/journals/evolutionary-human-sciences/article/methods-in-causal-inference-part-1-causal-diagrams-and-confounding/E734F72109F1BE99836E268DF3AA0359)

Beginner level covering essential concepts, DAGs, and confounding bias.

#### Part 2: [Interaction, Mediation, and Time-Varying Treatments](https://www.cambridge.org/core/journals/evolutionary-human-sciences/article/methods-in-causal-inference-part-2-interaction-mediation-and-timevarying-treatments/D7FD95D3ED64FE0FBBEC37AC6CEAFBC1)

Intermediate level covering effect modification and complex causal structures.

#### Part 3: [Measurement Error and External Validity](https://www.cambridge.org/core/journals/evolutionary-human-sciences/article/methods-in-causal-inference-part-3-measurement-error-and-external-validity-threats/4D35FFDECF32B2EFF7557EC26075175F)

Intermediate level focusing on measurement and cross-cultural validity.

#### Part 4: [Confounding in Experiments](https://www.cambridge.org/core/journals/evolutionary-human-sciences/article/methods-in-causal-inference-part-4-confounding-in-experiments/570D60A5FCCA007B55427384818C368E)

Advanced level covering experimental design considerations.

::: {#getting-started-with-r-and-causal-tools .callout-tip}
## Getting Started with R and Causal Tools
For an interactive introduction to directed acyclic graphs, see [Introduction to Directed Acyclic Graphs](https://r-causal.github.io/ggdag/articles/intro-to-dags.html). For a visual guide to common bias structures, see [Common Structures of Bias](https://r-causal.github.io/ggdag/articles/bias-structures.html). For propensity score weighting, start with the [WeightIt documentation](https://ngreifer.github.io/WeightIt/).
:::

---

## Software and Tools

### R Packages

::: {.panel-tabset}

#### Causal Inference

**margot**
A framework for causal inference with panel data, supporting doubly robust estimation and sensitivity analyses. Documentation is at [go-bayes.github.io/margot](https://go-bayes.github.io/margot/), and the source code is at [github.com/go-bayes/margot](https://github.com/go-bayes/margot/). Install with `devtools::install_github("go-bayes/margot")`.


**ggdag**
Create directed acyclic graphs for causal inference. Documentation is at [r-causal.github.io/ggdag](https://r-causal.github.io/ggdag/), and the CRAN page is [cran.r-project.org/package=ggdag](https://cran.r-project.org/package=ggdag). Install with `install.packages("ggdag")`.

**WeightIt**
Weighting for covariate balance in observational studies. Documentation is at [ngreifer.github.io/WeightIt](https://ngreifer.github.io/WeightIt/), and the CRAN page is [cran.r-project.org/package=WeightIt](https://cran.r-project.org/package=WeightIt). Install with `install.packages("WeightIt")`.

#### Research Tools

**boilerplate**
Tools for generating standardised boilerplate text and documentation for reproducible research. Documentation is at [go-bayes.github.io/boilerplate](https://go-bayes.github.io/boilerplate/), and the CRAN page is [cran.r-project.org/package=boilerplate](https://cran.r-project.org/package=boilerplate). Install with `install.packages("boilerplate")`.

:::

---

## Essential Readings

::: {.panel-tabset}

### Causal Diagrams and DAGs

**Core Readings**
Barrett, M. (2023). [ggdag: Analyze and Create Elegant Directed Acyclic Graphs](https://github.com/malcolmbarrett/ggdag).

Suzuki, E. et al. (2020). [Causal Diagrams: Pitfalls and Tips](https://www.dropbox.com/scl/fi/4midxwr9ltg9oce02e0ss/suzuki-causal-diagrams.pdf?rlkey=uktzf3nurtgpbj8m4h0xz82dn&dl=0). Intermediate level.

Neal, B. (2020). [Introduction to Causal Inference](https://www.bradyneal.com/Introduction_to_Causal_Inference-Dec17_2020-Neal.pdf), Chapter 3. Beginner level.

**On the Importance of Timing in Data**
Hernan, M.A. and Robins, J.M. (2024). [Causal Inference: What If](https://www.dropbox.com/scl/fi/9hy6xw1g1o4yz94ip8cvd/hernanrobins_WhatIf_2jan24.pdf?rlkey=8eaw6lqhmes7ddepuriwk5xk9&dl=0), Chapter 6. Advanced level.

### Effect Modification and Interaction

**Tutorial**
VanderWeele, T.J. and Knol, M.J. (2014). [A tutorial on interaction](https://www.degruyterbrill.com/document/doi/10.1515/em-2013-0005/html?lang=en&srsltid=AfmBOopUbFZ6aArax32MEBwLRB2jtM9nDST_KQ8XjhCuZ2fnNsrrvrij).

**Foundational Papers**
VanderWeele, T.J. (2007). [Four Types of Effect Modification](https://www.dropbox.com/scl/fi/drytp2ui2b8o9jplh4bm9/four_types_of_effect_modification__a.6.pdf?rlkey=mb9nl599v93m6kyyo69iv5nz1&dl=0). Intermediate level.

VanderWeele, T.J. (2009). [On the Distinction Between Interaction and Effect Modification](https://www.dropbox.com/scl/fi/srpynr0dvjcndveplcydn/OutcomeWide_StatisticalScience.pdf?rlkey=h4fv32oyjegdfl3jq9u1fifc3&dl=0). Intermediate level.

**Applied Methods**
Hernan, M.A. and Robins, J.M. (2024). [Causal Inference: What If](https://www.dropbox.com/scl/fi/9hy6xw1g1o4yz94ip8cvd/hernanrobins_WhatIf_2jan24.pdf?rlkey=8eaw6lqhmes7ddepuriwk5xk9&dl=0), Chapters 4-5. Intermediate level.

### Measurement and Cross-Cultural Validity

**Measurement Theory**
VanderWeele, T.J. (2022). [Constructed Measures and Causal Inference](https://www.dropbox.com/scl/fi/mmyguc0hrci8wtyyfkv6w/tyler-vanderweele-contruct-measures.pdf?rlkey=o18fiyajdqqpyjgssyh6mz6qm&dl=0). Advanced level.

Fischer, R. and Karl, J.A. (2019). [A Primer to (Cross-Cultural) Multi-Group Invariance Testing](https://www.dropbox.com/scl/fi/1h8slzy3vzscvbtp6yrjh/FischeKarlprimer.pdf?rlkey=xl93d5y7280c1qjhn3k2g8qls&dl=0). Intermediate level.

**Cross-Cultural Methods**
He, J. and Van de Vijver, F.J.R. (2012). [Bias and Equivalence in Cross-Cultural Research](https://www.dropbox.com/scl/fi/zuv4odmxbz8dbtdjfap3e/He-BiasandEquivalence.pdf?rlkey=wezprklb4jm6rgvvx0g58nw1n&dl=0). Intermediate level.

Harkness, J.A. (2003). [Questionnaire Translation](https://www.dropbox.com/scl/fi/hmmje9vbunmcu3oiahaa5/Harkness_CC_translation.pdf?rlkey=6vqq3ap5n52qp7t1e570ubpgt&dl=0). Beginner level.

### Selection Bias and Experimental Design

**Selection Bias**
Hernan, M.A. et al. (2004). [A Structural Approach to Selection Bias](https://www.dropbox.com/scl/fi/qni0y1lstntmdw410m2nh/Heran2004StructuralSelectionBias.pdf?rlkey=0ob86mmx7vscxqmn3ipg9m94f&dl=0). Advanced level.

Hernan, M.A. (2017). [Selection Without Colliders](https://www.dropbox.com/scl/fi/zr3tk7ngsutjprqr18bbg/hernan-selection-without-colliders.pdf?rlkey=vfluyl3a7zksfphqepao04fix&dl=0). Advanced level.

**Measurement Error**
Hernan, M.A. and Cole, S.R. (2009). [Causal Diagrams for Measurement Error](https://www.dropbox.com/scl/fi/ip8nil6uc5l0x9xw14mbr/hernan_cole_Measure_causal_diagrams.pdf?rlkey=wkj3ayen8xb6ncog46sps2g49&dl=0). Intermediate level.

### Practical Workflows

**Implementation Guides**
Bulbulia, J.A. (2024). [A Practical Guide to Causal Inference](https://osf.io/preprints/psyarxiv/uyg3d). Beginner level.

Hoffman, K.M. et al. (2023). [Comparison Groups in Propensity Score Analysis](https://arxiv.org/pdf/2304.09460.pdf). Intermediate level.

**Outcome-Wide Approaches**
VanderWeele, T.J. et al. (2020). [Outcome-Wide Longitudinal Designs](https://www.dropbox.com/scl/fi/srpynr0dvjcndveplcydn/OutcomeWide_StatisticalScience.pdf?rlkey=h4fv32oyjegdfl3jq9u1fifc3&dl=0). Intermediate level.

### Heterogeneous Treatment Effects

**Key Papers**
Athey, S. and Wager, S. (2019). [Estimating Treatment Effects with Causal Forests: An Application](https://arxiv.org/pdf/1902.07409.pdf). Intermediate level.

Wager, S. and Athey, S. (2018). [Estimation and Inference of Heterogeneous Treatment Effects using Random Forests](https://www.tandfonline.com/doi/full/10.1080/01621459.2017.1319839). Advanced level.

Kunzel, S.R. et al. (2019). [Metalearners for Estimating Heterogeneous Treatment Effects using Machine Learning](https://www.pnas.org/doi/10.1073/pnas.1804597116). Intermediate level.

**Practical Applications**
Davis, J. and Heller, S.B. (2017). [Using Causal Forests to Predict Treatment Heterogeneity](https://arxiv.org/pdf/1707.02641.pdf). Beginner level.

Athey, S. and Imbens, G.W. (2016). [Recursive Partitioning for Heterogeneous Causal Effects](https://www.pnas.org/doi/10.1073/pnas.1510489113). Intermediate level.

:::

---

## Video Library

#### How Do We Learn What Works?
*Miguel Hernan*

::: {.video-embed}
{{< video https://www.youtube.com/watch?v=NsVDfKiVGPc >}}
:::

#### Measurement Constructs
*Tyler VanderWeele*

::: {.video-embed}
{{< video https://www.youtube.com/watch?v=UA2WvYlT2RE&t=24s >}}
:::

### Effect Modification and Heterogeneity

*Stijn Vansteelandt and Betsy Ogburn*

::: {.video-embed}
{{< video https://www.youtube.com/watch?v=DkyNCJLWqUg&t=2827s >}}
:::

#### Introduction to Causal Forests
*Susan Athey and Stefan Wager*

::: {.video-embed}
{{< video https://www.youtube.com/watch?v=YBbnCDRCcAI&t=1241s >}}
:::

#### Technical Deep Dive: Causal Forests
*Stefan Wager*

::: {.video-embed}
{{< video https://www.youtube.com/watch?v=lBW4fwjCF44 >}}
:::

### How Traditional Statistical Mediation Analysis Fails

*Stijn Vansteelandt*

::: {.video-embed}
{{< video https://www.youtube.com/watch?v=IgC7R07Qk6A&t=953s >}}
:::


### Design

#### Synthetic Control Methods
*Alberto Abadie*

::: {.video-embed}
{{< video https://www.youtube.com/watch?v=nKzNp-qpE-I&list=PLoazKTcS0RzZ1SUgeOgc6SWt51gfT80N0&index=11 >}}
:::

#### Difference-in-Differences
*Paul Goldsmith-Pinkham*

::: {.video-embed}
{{< video https://www.youtube.com/watch?v=2nDgrNP7XSE&list=PLoazKTcS0RzZ1SUgeOgc6SWt51gfT80N0&index=10 >}}
:::

#### Instrumental Variables
*Brady Neal*

::: {.video-embed}
{{< video https://www.youtube.com/watch?v=B0SRWteGoOw&list=PLoazKTcS0RzZ1SUgeOgc6SWt51gfT80N0&index=9 >}}
:::

#### Introduction to Causal Inference
*Richard McElreath*

::: {.video-embed}
{{< video https://www.youtube.com/watch?v=KNPYUVmY3NM >}}
:::

#### Causal Inference in Industry
*Sean Taylor*

::: {.video-embed}
{{< video https://www.youtube.com/watch?v=YFnqi4srcKc&t=2915s >}}
:::

---

## Educational Materials

### Workshop Materials

The [SPARCC Causal Inference Workshop](https://go-bayes.github.io/sparcc-day-2/) offers a concise, practical entry point. For a full course sequence, see [PSYC 434: Conducting Research Across Cultures](https://go-bayes.github.io/psych-434-2025/).

---

## Reference Texts

### Core Textbooks

:::: {.columns}
::: {.column width="50%"}
**Causal Inference: What If**
*Miguel A. Hernan and James M. Robins*
[Free Book and Resources](https://miguelhernan.org/whatifbook). The definitive text on causal inference methods with code examples.
:::

::: {.column width="50%"}
**Explanation in Causal Inference**
*Tyler VanderWeele*
[Link to OUP page](https://global.oup.com/academic/product/explanation-in-causal-inference-9780199325870). A strong account of causal mediation analysis and interaction. The hardback is expensive, so a library copy is often the easiest option.
:::

::::

:::: {.columns}
::: {.column width="50%"}
**The Effect**
*Nick Huntington-Klein*
[Free Online](https://theeffectbook.net/). A practical guide with clear visualisations.
:::
::::

### Additional Resources

**Statistical Rethinking** by Richard McElreath provides a Bayesian approach to causal inference. **Counterfactuals and Causal Inference** by Morgan and Winship focuses on social science applications. **Targeted Learning** by van der Laan and Rose offers a machine learning perspective on causal inference.

---

## Quick Reference

::: {.callout-note}
## Where to Start
If you are new to causal inference, begin with our [four-part tutorial series](#learning-pathways). If you need DAGs, the [ggdag tutorials](#getting-started-with-r-and-causal-tools) are a good first step. If you are ready to analyse data, install [margot](#r-packages) and follow the [practical guide](https://osf.io/preprints/psyarxiv/uyg3d). For cross-cultural research, start with [Part 3](https://www.cambridge.org/core/journals/evolutionary-human-sciences/article/methods-in-causal-inference-part-3-measurement-error-and-external-validity-threats/4D35FFDECF32B2EFF7557EC26075175F) of the series.
:::

::: {.callout-tip}
## Contributing
Have a resource to suggest or a broken link to fix? Please [contact us](about.qmd) or submit an issue on our [GitHub repository](https://github.com/go-bayes/ottolab).
:::
